# coding: utf-8

"""
    WorldCat Search API v. 2

    Searching of WorldCat  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.bibs_oclc_number.get import RetrieveBib
from openapi_client.paths.brief_bibs_oclc_number.get import RetrieveBriefBib
from openapi_client.paths.brief_bibs_oclc_number_other_editions.get import RetrieveOtherEditions
from openapi_client.paths.bibs.get import SearchBibs
from openapi_client.paths.brief_bibs.get import SearchBriefBibs


class BibliographicResourcesApi(
    RetrieveBib,
    RetrieveBriefBib,
    RetrieveOtherEditions,
    SearchBibs,
    SearchBriefBibs,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
