# coding: utf-8

"""
    WorldCat Search API v. 2

    Searching of WorldCat  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.bibs_retained_holdings.get import FindBibRetainedHoldings


class MemberSharedPrintHoldingsApi(
    FindBibRetainedHoldings,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
